from datetime import datetime
from typing import Any
from sqlalchemy import DateTime, Float, ForeignKey, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.session import Base
class Conversation(Base):
    __tablename__='conversations'; id:Mapped[str]=mapped_column(String(64),primary_key=True); title:Mapped[str]=mapped_column(String(255),index=True); turns:Mapped[list[dict[str,Any]]]=mapped_column(JSON,default=list); tags:Mapped[list[str]]=mapped_column(JSON,default=list); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class EvaluationJob(Base):
    __tablename__='evaluation_jobs'; id:Mapped[str]=mapped_column(String(64),primary_key=True); conversation_id:Mapped[str|None]=mapped_column(String(64),ForeignKey('conversations.id'),nullable=True); status:Mapped[str]=mapped_column(String(32),default='queued',index=True); error:Mapped[str|None]=mapped_column(Text,nullable=True); progress:Mapped[float]=mapped_column(Float,default=0.0); request_payload:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict); result_summary:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); turn_results:Mapped[list['TurnResult']]=relationship(back_populates='job',cascade='all, delete-orphan')
class TurnResult(Base):
    __tablename__='turn_results'; id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); job_id:Mapped[str]=mapped_column(String(64),ForeignKey('evaluation_jobs.id'),index=True); turn_index:Mapped[int]=mapped_column(Integer,index=True); speaker:Mapped[str]=mapped_column(String(128),default='unknown'); text:Mapped[str]=mapped_column(Text); context_analysis:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict); routed_facets:Mapped[list[str]]=mapped_column(JSON,default=list); consistency_alerts:Mapped[list[dict[str,Any]]]=mapped_column(JSON,default=list); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); job:Mapped[EvaluationJob]=relationship(back_populates='turn_results'); facet_scores:Mapped[list['FacetScore']]=relationship(back_populates='turn_result',cascade='all, delete-orphan')
class FacetScore(Base):
    __tablename__='facet_scores'; id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); turn_result_id:Mapped[int]=mapped_column(Integer,ForeignKey('turn_results.id'),index=True); facet_id:Mapped[str]=mapped_column(String(64),index=True); facet_name:Mapped[str]=mapped_column(String(255)); domain:Mapped[str]=mapped_column(String(16),index=True); score:Mapped[int]=mapped_column(Integer); confidence:Mapped[float]=mapped_column(Float,default=0.0); confidence_interval:Mapped[list[float]]=mapped_column(JSON,default=list); agreement_score:Mapped[float]=mapped_column(Float,default=0.0); reasoning:Mapped[str]=mapped_column(Text,default=''); adjustment:Mapped[str]=mapped_column(Text,default=''); raw_outputs:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict); review_flags:Mapped[list[str]]=mapped_column(JSON,default=list); turn_result:Mapped[TurnResult]=relationship(back_populates='facet_scores')
